### ISSUE TITLE
[질문]요구사항에 대한 질문입니다.

### ISSUE THREAD

**Issue by DavidYang2149** [CodeSoom/week1-assignment-2#31]
**구현할 기능들** 중에서
-  숫자를 연속해서 누르면 숫자가 더해져서 출력되어야 합니다.    

라는 조건이 있는데 **예시.gif**를 보면 1, 4, 6를 눌렀을 경우 146이 되는 것으로 이해했습니다.

Q. 만약 0으로 시작하여 연속적으로 숫자를 클릭했을 경우는 어떻게 처리하면 될지 알고 싶습니다.
ex) 0, 1, 5 클릭한 경우 : A. 015로 뷰에 출력 되지만 15로 처리. / B. 15로 뷰에 출력되고 15로 처리.

**Comment by wholemann** [comment]
이곳에 남기시면 저희가 확인을 하기 어렵습니다.

질문은 DM에 부탁드립니다.

**Comment by DavidYang2149** [comment]
네! 알겠습니다~

**Comment by wholemann** [comment]
DM 또는 리액트2기 채널이 좋겠군요ㅎㅎ 토론이 좋거든요. 트레이너만의 견해만이 정답이 아니기 때문이죠ㅎㅎ

**Comment by DavidYang2149** [comment]
네 😃. 
이번 건은 논의하기에는 시간이 지나서 close로 전환했습니다. 
다음 기회가 있을 때는 리액트2기 채널에 올려보겠습니다~!
